Added generator logic
openzim/devdocs pull request #10
Opened 2024-08-10 19:42 UTC by josephlewis42

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/assets/README.md
> +devdocs_48.png is adapted from:
see if we can use common logic to resize rather than adapt

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/client.py
> +    def sort_precedence(self) -> SortPrecedence:
test

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/client.py
> +    def build_navigation(self) -> list[NavigationSection]:
test

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/client.py
> +    type: str | None
note about nones

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/client.py
> +        for entry in self.entries:
itertools.groupby?

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/client.py
> +        for section in self.types:
itertools.groupby

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +        self.license_path = self.asset_path("LICENSE")
assert initializes

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +    def load_common_files(self) -> list[StaticItem]:
test

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +    def generate_zim(
test e2e

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +        # Explicitly inject the index.
note why we have to do this

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +        nav_sections = index.build_navigation()
rename navigation

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +            self.generate_zim(
Add TODO for progress

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +        page_to_title: dict[str, str] = {}
extract and test

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +        render_delta = 0.0
remove timers

2024-08-10 19:55 UTC, josephlewis42 commented on tests/test_basic.py
> +# pyright: strict, reportUnusedExpression=false
drop

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/templates/page.html
> +{# Devdocs is an SPA so each page will have (nearly) identical content. #}
add note about all the `| safes`

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/templates/license.html
> +{# Devdocs is an SPA so each page will have (nearly) identical content. #}
Fix header content

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/templates/page.html
> +{# Devdocs is an SPA so each page will have (nearly) identical content. #}
Add note about CSS

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +            Language=LANGUAGE_ISO_639_3,
Why constant?

2024-08-10 19:55 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +        if zim_path.exists():
Note about clobber

2024-08-10 21:25 UTC, josephlewis42 commented on src/devdocs2zim/client.py
> +        for section in self.types:
doesn't make this cleaner, ignoring

2024-08-12 18:27 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +    def page_titles(pages: list[DevdocsIndexEntry]) -> dict[str, str]:
test

2024-08-12 18:27 UTC, josephlewis42 commented on src/devdocs2zim/assets/COPYRIGHT
> +Copyright 2013-2024 Thibaut Courouble and other contributors
move to third_party/devdocs

2024-09-09 19:36 UTC, benoit74 commented
Hi @josephlewis42, thank you very much, I will review this tomorrow, I missed the notification in the avalanche I got when coming back from holidays, sorry for that!

2024-09-10 07:06 UTC, benoit74 requested changes
See few inline comments

I've created a ZIM of lua~5.4 and cpp. I will open separate issues to discuss what I've found there (nothing which is a blocker to merge this code, more stuff to be discussed / fixed before releasing a 0.1.0 version)

Regarding the time it takes to complete, I'm not that surprised. cpp tooks 15 minutes to complete, which is OK. We are used to scraper taking hours or even sometime days to complete, so this is not a concern from my PoV. But still good to mention and try to enhance, the faster the scraper can be the better.

Regarding known limitations, I suggest we open one issue per limitation so that we can discuss separately how to address them (or even decide to not address them ^^). I agree we do not need to fix them before the MVP.

2024-09-11 17:04 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +                logger.debug(f"  Progress {counter} / {len(page_to_title)} pages ")
That works for me! We can also emit the JSON progress data for the overall progress but I thought that would be a little too much to do in this PR.

2024-09-11 17:43 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +                should_compress=True,
I think I made a bad assumption here, the Godot tutorial which had lots of images is slow, but those images aren't in-lined (tracking that in #21). I had opened the file in Kiwix not realizing that Kiwix will load web resources so I assumed everything was in that `db.json` file that DevDocs caches in LocalStorage.

Instead, I think the biggest contributor is the navbar. As far as I can tell, the entries need to be rendered as relative links on every page (until we use JS) which can easily double the size of every page.

An alternative could be to just render the section the user is in and link section titles to the first page in that section.

2024-09-11 17:53 UTC, josephlewis42 commented on src/devdocs2zim/generator.py
> +    "<p>This is an error with DevDocs, not your ZIM reader e.g. Kiwix.</p>"
SGTM, I also added a warning when this happens. I only saw it happen once in the Bash documentation and I think it's fixed now.

2024-09-12 06:40 UTC, benoit74 commented on src/devdocs2zim/generator.py
> +                should_compress=True,
Let's live with it for now, and will see how this moves forward in next iterations

2024-09-12 06:40 UTC, benoit74 approved these changes

2024-09-12 06:40 UTC, merged