Initialized repository from template
openzim/devdocs pull request #2
Opened 2024-07-06 00:05 UTC by josephlewis42

Initialized repository from the Python bootstrap template here: https://github.com/openzim/_python-bootstrap.

Part of #1

2024-07-08 07:35 UTC, benoit74 requested changes
Very good, few things to fix but already mostly OK, thank you!

A scraper is supposed to support only one Python version (3.12 as of now) since it is not meant to be reused in a "bigger soft" (like a library would). Supporting multiple Python version is hence unneeded additional work, since it is very likely it will be useless. 

You also need at some point to update the dependencies used to latest versions (in pyproject.toml, but also in .pre-commit-config.yaml). Doing this in every PR is a pain and unneeded, but since this is the initial one I suggest you update dependencies to latest versions now, and we will do it once again just before releasing the first version of this scraper.

Regarding last point, you should definitely have a look at https://github.com/openzim/_python-bootstrap/pull/45

2024-07-08 23:36 UTC, josephlewis42 commented
> You also need at some point to update the dependencies used to latest versions (in pyproject.toml, but also in .pre-commit-config.yaml). Doing this in every PR is a pain and unneeded, but since this is the initial one I suggest you update dependencies to latest versions now, and we will do it once again just before releasing the first version of this scraper.

Does dependabot work with how these repos are set up or is there a strong preference for using specifically tagged versions?

2024-07-09 05:06 UTC, benoit74 commented on Dockerfile
> +FROM python:3.11-slim-bookworm
Looks like I forgot this one in my PR from yesterday, yes please open a PR with this.

2024-07-09 05:16 UTC, kelson42 commented
I would recommend to make a basic README file similar to in other repos.

2024-07-09 05:28 UTC, benoit74 requested changes
LGTM, only one last thing I failed to find in first review, sorry for that.

Since otherwise everything is OK, please directly do the modification and rewrite the commit history of your branch to only keep meaningful commits (i.e. squash / fixup commits). The goal is to remove commits like "Fixed PR comments". These commits are more linked to the review process and won't bring much value / make maintenance harder in one or two years ... This will obviously require a force push on your branch, but this is OK once review is over (or mostly over) - but avoid to do this before the end of the review, since otherwise it makes the second review harder.

2024-07-09 05:28 UTC, benoit74 commented on pyproject.toml
> +
I just realized that you miss a section to configure and trigger the automatic population of authors, classifiers, keywords, license and urls metadata with hatch-openzim plugin.

Following configuration is probably OK to populate default metadata for scrapers + add a "devdocs" keyword.
```
[tool.hatch.metadata.hooks.openzim-metadata]
kind = "scraper"
additional-keywords = ["devdocs"]
```

At least this is the "usual" configuration on other scrapers, see e.g.:
- https://github.com/openzim/ted/blob/main/pyproject.toml#L23-L25
- https://github.com/openzim/youtube/blob/main/scraper/pyproject.toml#L27-L29

2024-07-09 05:31 UTC, benoit74 commented
> I would recommend to make a basic README file similar to in other repos.

You mean, something more targeted towards usage by everyone rather than how to develop? I considered this would come in another PR once the software has settled, I don't think we already know how the software will really work / which parameters will be necessary. But yes, this is going to be needed.

2024-07-09 18:13 UTC, josephlewis42 commented on Dockerfile
> +FROM python:3.11-slim-bookworm
Created: https://github.com/openzim/_python-bootstrap/pull/46

2024-07-09 19:47 UTC, josephlewis42 commented
> This will obviously require a force push on your branch, but this is OK once review is over (or mostly over) - but avoid to do this before the end of the review, since otherwise it makes the second review harder.

Done! I didn't realize that "Squash and Merge" was disabled on this repo.

> I would recommend to make a basic README file similar to in other repos.

I added a bit more here with some example flags and installation instructions. There's still the warning that they're for example purposes only.

2024-07-10 12:11 UTC, benoit74 approved these changes
LGTM, thank you !

2024-07-10 12:13 UTC, merged