Added syntax highlighting
openzim/devdocs pull request #36
Opened 2024-11-03 04:40 UTC by josephlewis42

Fixes #30 

This PR adds syntax highlighting to our produced JS bundle. Because we're not an SPA yet I just used a document listener to call render but I'm open to other suggestions if there's a better way.

Here's the outcome with ZIM in Kiwix on the left and DevDocs on the right -- overall a pretty significant readability improvement to most of these docs:

![image](https://github.com/user-attachments/assets/36f299c2-a157-4102-94dc-93525b990962)

2024-11-03 21:33 UTC, benoit74 approved these changes
Pretty straightforward once you know how to do it! ^^

LGTM

2024-11-03 21:33 UTC, benoit74 requested changes
Oh no, sorry, we miss the CHANGELOG.md entry

2024-11-03 21:55 UTC, josephlewis42 commented
Whoops! Added the CHANGELOG entry.

2024-11-04 07:50 UTC, benoit74 approved these changes

2024-11-04 07:50 UTC, merged